/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/alerts` | `/alerts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/analytics` | `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/devices` | `/devices`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/device/[id]` | `/device/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/device/[id]/history` | `/device/[id]/history`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/device/[id]/leak` | `/device/[id]/leak`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/alerts` | `/alerts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/analytics` | `/analytics`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/devices` | `/devices`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/device/[id]` | `/device/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/device/[id]/history` | `/device/[id]/history`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/device/[id]/leak` | `/device/[id]/leak`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/alerts${`?${string}` | `#${string}` | ''}` | `/alerts${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/analytics${`?${string}` | `#${string}` | ''}` | `/analytics${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/devices${`?${string}` | `#${string}` | ''}` | `/devices${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/alerts` | `/alerts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/analytics` | `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/devices` | `/devices`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | `${'/(app)'}/device/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/device/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/device/${Router.SingleRoutePart<T>}/history${`?${string}` | `#${string}` | ''}` | `/device/${Router.SingleRoutePart<T>}/history${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/device/${Router.SingleRoutePart<T>}/leak${`?${string}` | `#${string}` | ''}` | `/device/${Router.SingleRoutePart<T>}/leak${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(app)'}/device/[id]` | `/device/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/device/[id]/history` | `/device/[id]/history`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/device/[id]/leak` | `/device/[id]/leak`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
