services:
  postgres:
    image: postgres:16-alpine
    container_name: smartwatt-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: smartwatt
      POSTGRES_USER: smartwatt
      POSTGRES_PASSWORD: smartwatt
    ports:
      - "5432:5432"

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: smartwatt-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    environment:
      MOSQUITTO_USERNAME: smartwatt
      MOSQUITTO_PASSWORD: smartwatt
    volumes:
      - ./mosquitto/:/mosquitto/
    command: >
      sh -c "mosquitto -c /mosquitto/mosquitto.conf"
