[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/knolleary/pubsubclient
    https://github.com/bblanchon/ArduinoJson
    https://github.com/adafruit/adafruit-gfx-library
    https://github.com/adafruit/adafruit-st7735-library
    https://github.com/mandulaj/PZEM-004T-v30
